export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  OWNER = "OWNER",
  CUSTOMER = "CUSTOMER",
}

export enum Permission {
  // Store & Owners
  MANAGE_STORES = "MANAGE_STORES",
  MANAGE_OWNERS = "MANAGE_OWNERS",
  VIEW_OWN_STORE = "VIEW_OWN_STORE",

  // Products & Inventory
  CREATE_PRODUCT = "CREATE_PRODUCT",
  UPDATE_PRODUCT = "UPDATE_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  MANAGE_ALL_PRODUCTS = "MANAGE_ALL_PRODUCTS",

  // Appointments
  BOOK_APPOINTMENT = "BOOK_APPOINTMENT",
  VIEW_OWN_APPOINTMENTS = "VIEW_OWN_APPOINTMENTS",
  MANAGE_STORE_APPOINTMENTS = "MANAGE_STORE_APPOINTMENTS",
  MANAGE_ALL_APPOINTMENTS = "MANAGE_ALL_APPOINTMENTS",

  // Prescriptions
  UPLOAD_PRESCRIPTION = "UPLOAD_PRESCRIPTION",
  VIEW_OWN_PRESCRIPTION = "VIEW_OWN_PRESCRIPTION",
  VIEW_STORE_PRESCRIPTIONS = "VIEW_STORE_PRESCRIPTIONS",
  MANAGE_ALL_PRESCRIPTIONS = "MANAGE_ALL_PRESCRIPTIONS",

  // Orders & Payments
  CREATE_ORDER = "CREATE_ORDER",
  VIEW_OWN_ORDERS = "VIEW_OWN_ORDERS",
  MANAGE_STORE_ORDERS = "MANAGE_STORE_ORDERS",
  MANAGE_ALL_ORDERS = "MANAGE_ALL_ORDERS",

  // Analytics & Audits
  VIEW_STORE_ANALYTICS = "VIEW_STORE_ANALYTICS",
  VIEW_GLOBAL_ANALYTICS = "VIEW_GLOBAL_ANALYTICS",
  VIEW_AUDIT_LOGS = "VIEW_AUDIT_LOGS",
  MANAGE_SETTINGS = "MANAGE_SETTINGS",
}

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.SUPER_ADMIN]: Object.values(Permission),
  [Role.OWNER]: [
    Permission.VIEW_OWN_STORE,
    Permission.CREATE_PRODUCT,
    Permission.UPDATE_PRODUCT,
    Permission.DELETE_PRODUCT,
    Permission.MANAGE_STORE_APPOINTMENTS,
    Permission.VIEW_STORE_PRESCRIPTIONS,
    Permission.MANAGE_STORE_ORDERS,
    Permission.VIEW_STORE_ANALYTICS,
  ],
  [Role.CUSTOMER]: [
    Permission.BOOK_APPOINTMENT,
    Permission.VIEW_OWN_APPOINTMENTS,
    Permission.UPLOAD_PRESCRIPTION,
    Permission.VIEW_OWN_PRESCRIPTION,
    Permission.CREATE_ORDER,
    Permission.VIEW_OWN_ORDERS,
  ],
};

export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFLICT: "CONFLICT",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  DISPOSABLE_EMAIL: "DISPOSABLE_EMAIL",
  SLOT_UNAVAILABLE: "SLOT_UNAVAILABLE",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
} as const;
